In [16]:
import pandas as pd 

data = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")
test_ids = test["PassengerId"]

In [17]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [18]:
def clean(data):
    
    cols = ["SibSp", "Parch", "Fare", "Age"]
    classes = [1, 2, 3]

    for col in cols:
        for clas in classes:
            median = data.loc[data["Pclass"] == clas, col].median()

            data.loc[
                (data["Pclass"] == clas) & (data[col].isna()),
                col
            ] = median

    data["Embarked"] = data["Embarked"].fillna("U")

    return data

data = clean(data)
test = clean(test)

In [19]:
# feature engineer 
for df in [data,test]:
    df["family_size"] = df["Parch"] + df["SibSp"] + 1
    df["is_child"] = (df["Age"] < 14).astype(int)
    df["is_alone"] = (df["family_size"] == 1).astype(int)
    df["Title"] = df["Name"].str.extract(r",\s*([^.]*)\.")

In [20]:
data = data.drop(["Cabin","Name", "PassengerId"],axis=1)
test = test.drop(["Cabin","Name", "PassengerId"],axis=1)

In [21]:
print (data["Ticket"].nunique())

681

In [22]:
print(len(data))

891

In [23]:
ticket_counts = pd.concat([data["Ticket"], test["Ticket"]]).value_counts()
for df in [data, test]:
    df["TicketGroupSize"] = df["Ticket"].map(ticket_counts)

In [24]:
data

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,family_size,is_child,is_alone,Title,TicketGroupSize
0,0,3,male,22.0,1,0,A/5 21171,7.2500,S,2,0,0,Mr,1
1,1,1,female,38.0,1,0,PC 17599,71.2833,C,2,0,0,Mrs,2
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,S,1,0,1,Miss,1
3,1,1,female,35.0,1,0,113803,53.1000,S,2,0,0,Mrs,2
4,0,3,male,35.0,0,0,373450,8.0500,S,1,0,1,Mr,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,211536,13.0000,S,1,0,1,Rev,1
887,1,1,female,19.0,0,0,112053,30.0000,S,1,0,1,Miss,1
888,0,3,female,24.0,1,2,W./C. 6607,23.4500,S,4,0,0,Miss,4
889,1,1,male,26.0,0,0,111369,30.0000,C,1,0,1,Mr,1
890,0,3,male,32.0,0,0,370376,7.7500,Q,1,0,1,Mr,1

In [25]:
data = data.drop("Ticket" , axis = 1)

In [26]:
agemean = data["Age"].mean()
agestd = data["Age"].std()
faremean = data["Fare"].mean()
farestd = data["Fare"].std()

data["Age"] = (data["Age"]-agemean)/agestd
test["Age"] = (test["Age"] - agemean) / agestd

data["Fare"] = (data["Fare"]-faremean)/farestd
test["Fare"] = (test["Fare"] - faremean) / farestd

In [27]:
data

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,family_size,is_child,is_alone,Title,TicketGroupSize
0,0,3,male,-0.533534,1,0,-0.502163,S,2,0,0,Mr,1
1,1,1,female,0.674512,1,0,0.786404,C,2,0,0,Mrs,2
2,1,3,female,-0.231523,0,0,-0.488580,S,1,0,1,Miss,1
3,1,1,female,0.448003,1,0,0.420494,S,2,0,0,Mrs,2
4,0,3,male,0.448003,0,0,-0.486064,S,1,0,1,Mr,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,-0.156020,0,0,-0.386454,S,1,0,1,Rev,1
887,1,1,female,-0.760043,0,0,-0.044356,S,1,0,1,Miss,1
888,0,3,female,-0.382528,1,2,-0.176164,S,4,0,0,Miss,4
889,1,1,male,-0.231523,0,0,-0.044356,C,1,0,1,Mr,1
890,0,3,male,0.221495,0,0,-0.492101,Q,1,0,1,Mr,1

In [28]:
data["Sex"] = data["Sex"].map({"male": 0, "female": 1})
test["Sex"] = test["Sex"].map({"male": 0, "female": 1})
data = pd.get_dummies(data, columns=["Embarked","Pclass", "Title"], dtype=int)
test = pd.get_dummies(test, columns=["Embarked","Pclass", "Title"], dtype=int)

test = test.reindex(columns=data.drop("Survived", axis=1).columns, fill_value=0)

KeyError: "None of [Index(['Embarked', 'Pclass', 'Title'], dtype='str')] are in the [columns]"

In [30]:
data

,Survived,Sex,Age,SibSp,Parch,Fare,family_size,is_child,is_alone,TicketGroupSize,...,Title_Master,Title_Miss,Title_Mlle,Title_Mme,Title_Mr,Title_Mrs,Title_Ms,Title_Rev,Title_Sir,Title_the Countess
0,0,NaN,-0.533534,1,0,-0.502163,2,0,0,1,...,0,0,0,0,1,0,0,0,0,0
1,1,NaN,0.674512,1,0,0.786404,2,0,0,2,...,0,0,0,0,0,1,0,0,0,0
2,1,NaN,-0.231523,0,0,-0.488580,1,0,1,1,...,0,1,0,0,0,0,0,0,0,0
3,1,NaN,0.448003,1,0,0.420494,2,0,0,2,...,0,0,0,0,0,1,0,0,0,0
4,0,NaN,0.448003,0,0,-0.486064,1,0,1,1,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,NaN,-0.156020,0,0,-0.386454,1,0,1,1,...,0,0,0,0,0,0,0,1,0,0
887,1,NaN,-0.760043,0,0,-0.044356,1,0,1,1,...,0,1,0,0,0,0,0,0,0,0
888,0,NaN,-0.382528,1,2,-0.176164,4,0,0,4,...,0,1,0,0,0,0,0,0,0,0
889,1,NaN,-0.231523,0,0,-0.044356,1,0,1,1,...,0,0,0,0,1,0,0,0,0,0
890,0,NaN,0.221495,0,0,-0.492101,1,0,1,1,...,0,0,0,0,1,0,0,0,0,0

In [31]:
x_train = data.drop("Survived", axis = 1)
y_train = data["Survived"]

In [65]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

x_train, x_dev, y_train, y_dev = train_test_split(x_train,y_train, test_size = 0.15, random_state=42)

In [68]:
from sklearn.linear_model import LogisticRegression
import optuna 
from sklearn.model_selection import cross_val_score

def objective(trial):
    n_estimators = trial.suggest_int("n_estimators", 50, 200)
    max_depth = trial.suggest_int("max_depth", 2, 10)
    min_samples_split = trial.suggest_int("min_samples_split", 2, 10)
    min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 10)
    max_features = trial.suggest_categorical("max_features",["sqrt", "log2", None])

    clf = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        max_features=max_features,
        random_state=42,
        n_jobs=-1
    )

    score = cross_val_score(clf, x_train, y_train, cv = 5, scoring = "accuracy").mean()

    return score 

study = optuna.create_study(direction="maximize")
study.optimize(objective,n_trials=200)

print(study.best_value)
print(study.best_params)

[I 2026-08-22 22:42:24,424] A new study created in memory with name: no-name-c123d37b-f6a2-48ac-b9c6-c029320392f2
[I 2026-08-22 22:42:25,187] Trial 0 finished with value: 0.8192763157894737 and parameters: {'n_estimators': 164, 'max_depth': 4, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 0 with value: 0.8192763157894737.
[I 2026-08-22 22:42:26,010] Trial 1 finished with value: 0.8129605263157893 and parameters: {'n_estimators': 176, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 0 with value: 0.8192763157894737.
[I 2026-08-22 22:42:26,469] Trial 2 finished with value: 0.8234649122807017 and parameters: {'n_estimators': 91, 'max_depth': 5, 'min_samples_split': 9, 'min_samples_leaf': 9, 'max_features': 'log2'}. Best is trial 2 with value: 0.8234649122807017.
[I 2026-08-22 22:42:26,957] Trial 3 finished with value: 0.8192543859649122 and parameters: {'n_estimators': 93, 'max_depth': 10, 'min_samples_split': 9, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 2 with value: 0.8234649122807017.
[I 2026-08-22 22:42:27,670] Trial 4 finished with value: 0.8234649122807017 and parameters: {'n_estimators': 159, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 8, 'max_features': 'sqrt'}. Best is trial 2 with value: 0.8234649122807017.
[I 2026-08-22 22:42:28,028] Trial 5 finished with value: 0.8234868421052631 and parameters: {'n_estimators': 60, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 5 with value: 0.8234868421052631.
[I 2026-08-22 22:42:28,636] Trial 6 finished with value: 0.8213815789473683 and parameters: {'n_estimators': 125, 'max_depth': 2, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': 'log2'}. Best is trial 5 with value: 0.8234868421052631.
[I 2026-08-22 22:42:29,520] Trial 7 finished with value: 0.8108552631578947 and parameters: {'n_estimators': 176, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 5 with value: 0.8234868421052631.
[I 2026-08-22 22:42:29,956] Trial 8 finished with value: 0.817171052631579 and parameters: {'n_estimators': 78, 'max_depth': 4, 'min_samples_split': 2, 'min_samples_leaf': 7, 'max_features': 'log2'}. Best is trial 5 with value: 0.8234868421052631.
[I 2026-08-22 22:42:30,441] Trial 9 finished with value: 0.8129605263157895 and parameters: {'n_estimators': 96, 'max_depth': 10, 'min_samples_split': 8, 'min_samples_leaf': 4, 'max_features': 'log2'}. Best is trial 5 with value: 0.8234868421052631.
[I 2026-08-22 22:42:30,798] Trial 10 finished with value: 0.8192763157894737 and parameters: {'n_estimators': 54, 'max_depth': 2, 'min_samples_split': 7, 'min_samples_leaf': 5, 'max_features': 'sqrt'}. Best is trial 5 with value: 0.8234868421052631.
[I 2026-08-22 22:42:31,132] Trial 11 finished with value: 0.8255701754385966 and parameters: {'n_estimators': 51, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8255701754385966.
[I 2026-08-22 22:42:31,483] Trial 12 finished with value: 0.8213815789473685 and parameters: {'n_estimators': 51, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8255701754385966.
[I 2026-08-22 22:42:31,887] Trial 13 finished with value: 0.8108552631578947 and parameters: {'n_estimators': 68, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 'sqrt'}. Best is trial 11 with value: 0.8255701754385966.
[I 2026-08-22 22:42:32,460] Trial 14 finished with value: 0.8150657894736841 and parameters: {'n_estimators': 118, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 10, 'max_features': 'log2'}. Best is trial 11 with value: 0.8255701754385966.
[I 2026-08-22 22:42:32,879] Trial 15 finished with value: 0.8150877192982456 and parameters: {'n_estimators': 72, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 7, 'max_features': None}. Best is trial 11 with value: 0.8255701754385966.
[I 2026-08-22 22:42:33,260] Trial 16 finished with value: 0.8171710526315789 and parameters: {'n_estimators': 52, 'max_depth': 5, 'min_samples_split': 8, 'min_samples_leaf': 5, 'max_features': 'log2'}. Best is trial 11 with value: 0.8255701754385966.
[I 2026-08-22 22:42:33,828] Trial 17 finished with value: 0.8192763157894737 and parameters: {'n_estimators': 116, 'max_depth': 3, 'min_samples_split': 8, 'min_samples_leaf': 8, 'max_features': 'log2'}. Best is trial 11 with value: 0.8255701754385966.
[I 2026-08-22 22:42:34,740] Trial 18 finished with value: 0.8255701754385966 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 11 with value: 0.8255701754385966.
[I 2026-08-22 22:42:35,650] Trial 19 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 196, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 19 with value: 0.8276754385964912.
[I 2026-08-22 22:42:36,316] Trial 20 finished with value: 0.821359649122807 and parameters: {'n_estimators': 145, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 9, 'max_features': None}. Best is trial 19 with value: 0.8276754385964912.
[I 2026-08-22 22:42:37,239] Trial 21 finished with value: 0.829780701754386 and parameters: {'n_estimators': 198, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:38,161] Trial 22 finished with value: 0.8171271929824562 and parameters: {'n_estimators': 198, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:38,873] Trial 23 finished with value: 0.8255701754385966 and parameters: {'n_estimators': 139, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:39,751] Trial 24 finished with value: 0.8150219298245613 and parameters: {'n_estimators': 180, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:40,679] Trial 25 finished with value: 0.8234429824561402 and parameters: {'n_estimators': 190, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:41,452] Trial 26 finished with value: 0.8276535087719298 and parameters: {'n_estimators': 162, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:42,254] Trial 27 finished with value: 0.8255701754385966 and parameters: {'n_estimators': 164, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:43,143] Trial 28 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 187, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:44,030] Trial 29 finished with value: 0.8234868421052631 and parameters: {'n_estimators': 186, 'max_depth': 9, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:44,920] Trial 30 finished with value: 0.8255701754385966 and parameters: {'n_estimators': 190, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:45,652] Trial 31 finished with value: 0.8255701754385966 and parameters: {'n_estimators': 153, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:46,447] Trial 32 finished with value: 0.8192543859649122 and parameters: {'n_estimators': 171, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:47,259] Trial 33 finished with value: 0.8255482456140351 and parameters: {'n_estimators': 168, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:48,109] Trial 34 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 181, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:48,971] Trial 35 finished with value: 0.8234868421052631 and parameters: {'n_estimators': 183, 'max_depth': 10, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:49,864] Trial 36 finished with value: 0.8129605263157893 and parameters: {'n_estimators': 194, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:50,722] Trial 37 finished with value: 0.8255701754385966 and parameters: {'n_estimators': 176, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:51,662] Trial 38 finished with value: 0.8129166666666666 and parameters: {'n_estimators': 200, 'max_depth': 8, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:52,421] Trial 39 finished with value: 0.8255921052631578 and parameters: {'n_estimators': 154, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:53,297] Trial 40 finished with value: 0.8171710526315789 and parameters: {'n_estimators': 179, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 3, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:54,171] Trial 41 finished with value: 0.821359649122807 and parameters: {'n_estimators': 187, 'max_depth': 6, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:54,990] Trial 42 finished with value: 0.821359649122807 and parameters: {'n_estimators': 168, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:55,762] Trial 43 finished with value: 0.829780701754386 and parameters: {'n_estimators': 159, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:56,586] Trial 44 finished with value: 0.829780701754386 and parameters: {'n_estimators': 172, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:57,226] Trial 45 finished with value: 0.8276315789473683 and parameters: {'n_estimators': 139, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:58,058] Trial 46 finished with value: 0.829780701754386 and parameters: {'n_estimators': 174, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:58,819] Trial 47 finished with value: 0.8108552631578947 and parameters: {'n_estimators': 157, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:42:59,640] Trial 48 finished with value: 0.8255482456140351 and parameters: {'n_estimators': 173, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:00,343] Trial 49 finished with value: 0.8255701754385966 and parameters: {'n_estimators': 145, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:01,272] Trial 50 finished with value: 0.8276315789473683 and parameters: {'n_estimators': 194, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 3, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:02,173] Trial 51 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 191, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:03,557] Trial 52 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 184, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:05,039] Trial 53 finished with value: 0.8192324561403508 and parameters: {'n_estimators': 174, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:06,678] Trial 54 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 195, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:08,055] Trial 55 finished with value: 0.8192763157894737 and parameters: {'n_estimators': 163, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:09,378] Trial 56 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 149, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:10,799] Trial 57 finished with value: 0.8192543859649122 and parameters: {'n_estimators': 167, 'max_depth': 7, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:12,339] Trial 58 finished with value: 0.8150877192982456 and parameters: {'n_estimators': 177, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:13,925] Trial 59 finished with value: 0.8234868421052631 and parameters: {'n_estimators': 188, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:15,277] Trial 60 finished with value: 0.8213377192982456 and parameters: {'n_estimators': 159, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:16,584] Trial 61 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 181, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:17,774] Trial 62 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 183, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:19,425] Trial 63 finished with value: 0.8234868421052631 and parameters: {'n_estimators': 172, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:21,232] Trial 64 finished with value: 0.8192324561403508 and parameters: {'n_estimators': 195, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:22,256] Trial 65 finished with value: 0.8255701754385966 and parameters: {'n_estimators': 98, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:23,892] Trial 66 finished with value: 0.8234868421052631 and parameters: {'n_estimators': 178, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:25,590] Trial 67 finished with value: 0.8129824561403508 and parameters: {'n_estimators': 190, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 2, 'max_features': 'log2'}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:26,522] Trial 68 finished with value: 0.829780701754386 and parameters: {'n_estimators': 200, 'max_depth': 7, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:28,170] Trial 69 finished with value: 0.817171052631579 and parameters: {'n_estimators': 198, 'max_depth': 7, 'min_samples_split': 8, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:29,692] Trial 70 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 186, 'max_depth': 7, 'min_samples_split': 7, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:30,640] Trial 71 finished with value: 0.8255921052631578 and parameters: {'n_estimators': 200, 'max_depth': 6, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:31,562] Trial 72 finished with value: 0.8276754385964912 and parameters: {'n_estimators': 191, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:32,445] Trial 73 finished with value: 0.8276973684210527 and parameters: {'n_estimators': 181, 'max_depth': 9, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:33,286] Trial 74 finished with value: 0.8213815789473683 and parameters: {'n_estimators': 169, 'max_depth': 8, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:34,264] Trial 75 finished with value: 0.8129824561403508 and parameters: {'n_estimators': 195, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 2, 'max_features': 'sqrt'}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:35,076] Trial 76 finished with value: 0.8213815789473685 and parameters: {'n_estimators': 164, 'max_depth': 10, 'min_samples_split': 5, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:36,007] Trial 77 finished with value: 0.8192324561403508 and parameters: {'n_estimators': 184, 'max_depth': 9, 'min_samples_split': 7, 'min_samples_leaf': 2, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.
[I 2026-08-22 22:43:37,155] Trial 78 finished with value: 0.8276973684210527 and parameters: {'n_estimators': 178, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None}. Best is trial 21 with value: 0.829780701754386.

0.8318859649122807
{'n_estimators': 153, 'max_depth': 5, 'min_samples_split': 4, 'min_samples_leaf': 1, 'max_features': None}

In [69]:
best_clf = RandomForestClassifier(
    **study.best_params,
    random_state=42,
    n_jobs=-1
)

best_clf.fit(x_train, y_train)

RandomForestClassifier(max_depth=5, max_features=None, min_samples_split=4,
                       n_estimators=153, n_jobs=-1, random_state=42)

In [70]:
accuracy = best_clf.score(x_dev,y_dev)
print(accuracy)

0.8214285714285714

In [ ]:
submission_preds = best_clf.predict(test)

In [71]:


df = pd.DataFrame({"PassengerId":test_ids.values, "Survived" : submission_preds })

df.to_csv("submissionforest.csv", index = False)