In [61]:
import pandas as pd 

data = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")
test_ids = test["PassengerId"]

In [62]:


print(data.nunique())

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

In [63]:
first_class = data[data["Pclass"]==1]
second_class = data[data["Pclass"]==2]
third_class = data[data["Pclass"]==3]

In [64]:
print(first_class["Fare"].mean())


print(second_class["Fare"].mean())
print(third_class["Fare"].mean())

84.1546875
20.662183152173913
13.675550101832993

In [65]:
print("fraction who survived in first class")
print(len(first_class[first_class["Survived"]==1])/len(first_class))

print("fraction who survived in second class")
print(len(second_class[second_class["Survived"]==1])/len(second_class))

print("fraction who survived in third class")
print(len(third_class[third_class["Survived"]==1])/len(third_class))

fraction who survived in first class
0.6296296296296297
fraction who survived in second class
0.47282608695652173
fraction who survived in third class
0.24236252545824846

In [66]:
def clean(data):
    data = data.drop(["Ticket","Cabin", "Name", "PassengerId"], axis = 1)

    cols = ["SibSp", "Parch", "Fare", "Age"]
    for col in cols:
        data[col] = data[col].fillna(data[col].median())

        data["Embarked"] = data["Embarked"].fillna("U")
        #fill unknown values with na
        # we can try and infer mean of ages by seeing if first class, (generally older for age), and so on stuff like that 
    return data

data = clean(data)
test = clean(test)

In [67]:
data.head(5)

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
from sklearn import preprocessing 

le = preprocessing.LabelEncoder()

cols = ["Sex"]

for col in cols:
    data[col] = le.fit_transform(data[col])
    test[col] = le.transform(test[col])
data["Sex"] = data["Sex"].map({"male": 0, "female": 1})
test["Sex"] = test["Sex"].map({"male": 0, "female": 1})
data = pd.get_dummies(data, columns=["Embarked","Pclass"], dtype=int)
test = pd.get_dummies(test, columns=["Embarked","Pclass"], dtype=int)

test = test.reindex(columns=data.drop("Survived", axis=1).columns, fill_value=0)

data.head(5)

,Survived,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3
0,0,1,22.0,1,0,7.2500,0,0,1,0,0,0,1
1,1,0,38.0,1,0,71.2833,1,0,0,0,1,0,0
2,1,0,26.0,0,0,7.9250,0,0,1,0,0,0,1
3,1,0,35.0,1,0,53.1000,0,0,1,0,1,0,0
4,0,1,35.0,0,0,8.0500,0,0,1,0,0,0,1

In [69]:
agemean = data["Age"].mean()
agestd = data["Age"].std()
faremean = data["Fare"].mean()
farestd = data["Fare"].std()

data["Age"] = (data["Age"]-agemean)/agestd
test["Age"] = (test["Age"] - agemean) / agestd

data["Fare"] = (data["Fare"]-faremean)/farestd
test["Fare"] = (test["Fare"] - faremean) / farestd

In [70]:
data

,Survived,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3
0,0,1,-0.565419,1,0,-0.502163,0,0,1,0,0,0,1
1,1,0,0.663488,1,0,0.786404,1,0,0,0,1,0,0
2,1,0,-0.258192,0,0,-0.488580,0,0,1,0,0,0,1
3,1,0,0.433068,1,0,0.420494,0,0,1,0,1,0,0
4,0,1,0.433068,0,0,-0.486064,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,1,-0.181385,0,0,-0.386454,0,0,1,0,0,1,0
887,1,0,-0.795839,0,0,-0.044356,0,0,1,0,1,0,0
888,0,0,-0.104579,1,2,-0.176164,0,0,1,0,0,0,1
889,1,1,-0.258192,0,0,-0.044356,1,0,0,0,1,0,0
890,0,1,0.202648,0,0,-0.492101,0,1,0,0,0,0,1

In [71]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [72]:
for df in [data, test]:
    df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
    df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
    df["Child"] = (df["Age"] < 14).astype(int)

y = data["Survived"]
x= data.drop("Survived", axis=1)

In [73]:
x

,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S,Embarked_U,Pclass_1,Pclass_2,Pclass_3,FamilySize,IsAlone,Child
0,1,-0.565419,1,0,-0.502163,0,0,1,0,0,0,1,2,0,1
1,0,0.663488,1,0,0.786404,1,0,0,0,1,0,0,2,0,1
2,0,-0.258192,0,0,-0.488580,0,0,1,0,0,0,1,1,1,1
3,0,0.433068,1,0,0.420494,0,0,1,0,1,0,0,2,0,1
4,1,0.433068,0,0,-0.486064,0,0,1,0,0,0,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,1,-0.181385,0,0,-0.386454,0,0,1,0,0,1,0,1,1,1
887,0,-0.795839,0,0,-0.044356,0,0,1,0,1,0,0,1,1,1
888,0,-0.104579,1,2,-0.176164,0,0,1,0,0,0,1,4,0,1
889,1,-0.258192,0,0,-0.044356,1,0,0,0,1,0,0,1,1,1
890,1,0.202648,0,0,-0.492101,0,1,0,0,0,0,1,1,1,1

In [74]:
x_train,x_val,y_train,y_val = train_test_split(x,y,test_size = 0.2, random_state = 42)

In [ ]:
clf = LogisticRegression(random_state=0, max_iter=1000 ).fit(x_train,y_train)
predictions = clf.predict(x_val)
trainpredictions = clf.predict(x_train)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_val,predictions))
print(accuracy_score(y_train,trainpredictions))

In [76]:
print(clf.feature_names_in_)
print(test.columns)

['Sex' 'Age' 'SibSp' 'Parch' 'Fare' 'Embarked_C' 'Embarked_Q' 'Embarked_S'
 'Embarked_U' 'Pclass_1' 'Pclass_2' 'Pclass_3' 'FamilySize' 'IsAlone'
 'Child']
Index(['Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked_C', 'Embarked_Q',
       'Embarked_S', 'Embarked_U', 'Pclass_1', 'Pclass_2', 'Pclass_3',
       'FamilySize', 'IsAlone', 'Child'],
      dtype='str')

In [81]:
predictions = clf.predict(x_val)
trainpredictions = clf.predict(x_train)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_val,predictions))
print(accuracy_score(y_train,trainpredictions))

0.7932960893854749
0.8117977528089888

In [78]:
submission_preds = clf.predict(test)

df = pd.DataFrame({"PassengerId":test_ids.values, "Survived" : submission_preds })

In [79]:
df.to_csv("submission.csv", index = False)